#!/usr/bin/env bash
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no 
# argument passed
# Ping the IP 5 times

if [$# -eq 0]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [$# -gt 1]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1" -c 5
fi
